# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/SCPU/icf-v-p.xdc

# IP: ip/Pic/Pic.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pic || ORIG_REF_NAME==Pic} -quiet] -quiet
