# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Code/Vivado/Player/Player.cache/wt [current_project]
set_property parent.project_path E:/Code/Vivado/Player/Player.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_output_repo e:/Code/Vivado/Player/Player.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/I_mem.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/D_mem.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/test.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/2_D_mem.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/font_ascii_8_8.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/Pic320.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/Pic.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/white.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/Monika.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/Long.coe
add_files E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/Inst.coe
read_verilog -library xil_defaultlib {
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/Counter_3_IO.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/ctrl_encode_def.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/EXT.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/Enter.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/MIO_BUS.V
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/Multi_8CH32.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/PC.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/PWM.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/RF.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/SCPU.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/SPIO.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/SSeg7.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/VGA.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/VGA_BUS.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/VGA_Scan.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/alu.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/clk_div.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/ctrl.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/dm_controller.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/hazard.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/pipeline.v
  E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/top.v
}
read_ip -quiet E:/Code/Vivado/Player/Player.srcs/sources_1/ip/Pic/Pic.xci
set_property used_in_implementation false [get_files -all e:/Code/Vivado/Player/Player.srcs/sources_1/ip/Pic/Pic_ooc.xdc]

read_ip -quiet E:/Code/Vivado/Player/Player.srcs/sources_1/ip/RAM_B/RAM_B.xci
set_property used_in_implementation false [get_files -all e:/Code/Vivado/Player/Player.srcs/sources_1/ip/RAM_B/RAM_B_ooc.xdc]

read_ip -quiet E:/Code/Vivado/Player/Player.srcs/sources_1/ip/Font/Font.xci
set_property used_in_implementation false [get_files -all e:/Code/Vivado/Player/Player.srcs/sources_1/ip/Font/Font_ooc.xdc]

read_ip -quiet E:/Code/Vivado/Player/Player.srcs/sources_1/ip/ROM_D/ROM_D.xci
set_property used_in_implementation false [get_files -all e:/Code/Vivado/Player/Player.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc]

read_edif E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/SPIO.edf
read_edif E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/SSeg7.edf
read_edif E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/Multi_8CH32.edf
read_edif E:/Code/Vivado/Player/Player.srcs/sources_1/imports/SCPU/MIO_BUS.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Code/Vivado/Player/Player.srcs/constrs_1/imports/SCPU/icf-v-p.xdc
set_property used_in_implementation false [get_files E:/Code/Vivado/Player/Player.srcs/constrs_1/imports/SCPU/icf-v-p.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
