# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Code/Vivado/Player/Player.srcs/sources_1/ip/Font/Font.xci
# IP: The module: 'Font' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Code/Vivado/Player/Player.srcs/sources_1/ip/Font/Font_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Font'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Code/Vivado/Player/Player.srcs/sources_1/ip/Font/Font.xci
# IP: The module: 'Font' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Code/Vivado/Player/Player.srcs/sources_1/ip/Font/Font_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Font'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
